### ISSUE TITLE
provide link back to gerrit

### ISSUE THREAD

**Issue by stleusc** [tomaswolf/gerrit-gitblit-plugin#11]
For better integration it would be nice if there was an easy way back to the gerrit home page.
Maybe replacing GitBlit on top left corner with link to gerrit?

Also, some 'themeing' support?

**Comment by tomaswolf** [comment]
There _is_ a link back to the Gerrit home page: bottom right it says Gerrit-Gitblit-plugin v.XXX. "Gerrit" is a link to the home page of the Gerrit the plugin runs in, "Gitblit" is a link to [Gitblit](http://gitblit.com/), and "plugin-v.XXX" is a link to this GitHub project.

Gitblit does not offer real theming support, and I cannot add that in the plugin. You can change the header logo top left, see the [Gitblit documentation](http://gitblit.com/properties.html) (the web.headerLogo property).

Additionally, you can use in gitblit.properties the regex settings (also see the documentation) to make for instance Gerrit change ids in commit messages link back to the change in Gerrit.
