### ISSUE TITLE
Update this plugin to use the gitblit 1.7.1 update

### ISSUE THREAD

**Issue by paladox** [tomaswolf/gerrit-gitblit-plugin#12]
Please update this plugin to use the new 1.7.1 update. Or use the version straight of master branch since there were some changes that were reverted but were re uploaded again after the update. Things such as raw was fixed.

Also make it compatible with gerrit 2.12 please.

**Comment by paladox** [comment]
https://github.com/gitblit/gitblit

**Comment by paladox** [comment]
Also the develop branch was removed in favour of using the master branch.

**Comment by tomaswolf** [comment]
1. Current released version of Gerrit is 2.11.5. Once Gerrit 2.12 is officially released, I'll make sure that the plugin here works with it. I'm not building against unreleased versions or -rc versions.

2. Now that James finally has officially released a 1.7 version of Gitblit, I will in time move to that. I will not build against his master branch; only against what's in his [maven repository](http://gitblit.github.io/gitblit-maven/). If that is buggy (and I do see a few fixes since 1.7.1), I'll decide on a case-by-case basis.

**Comment by tomaswolf** [comment]
Update to Gerrit 2.12 done; see [release 2.12.162.1](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.12.162.1).

Update to Gitblit 1.7.1 plus maybe some post-release fixes will take some more time.

**Comment by paladox** [comment]
Ok thanks. Maybe we would want to wait for 1.7.2 to be released since some fixes the were meant for 1.7.1 got reverted because a merge of branch reverted some changes by mistake which were re added. Or maybe you would incorporate those fixes when you update gitblit. The fix is viewing raw files which is currently broken if you view in such as repo such as example/example/example.

**Comment by sschuberth** [comment]
FYI, I recently did upgrade Luca's original plugin to GitBlit 1.7.1 before I got aware of this fork. You can probably take a look at [my change](https://gerrit-review.googlesource.com/#/c/73751/) to copy over the necessary API changes.

**Comment by paladox** [comment]
Thanks. Is it possible to use the latest change of master branch since viewing raw files is fixed in the latest change of master branch. It was meant to be released in the 1.7.x release but was reverted by mistake when the develop branch was merged.

**Comment by sschuberth** [comment]
It's not possible unless there are some pre-built (snapshot) artifacts available that contain this change. I guess it really would make sense to just wait for 1.7.2 in this case.

**Comment by paladox** [comment]
raw was broken in 1.6 and 1.5 I think.

**Comment by tomaswolf** [comment]
I've published a pre-release version for Gerrit 2.12 based on Gitblit **1.7.1** (with two post-1.7.1 PRs gitblit/gitblit#957 and gitblit/gitblit#983). See release [v2.12.171.0](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.12.171.0).

Give it a try, and please report back whether it works or has problems. I didn't spot any.

**Comment by tomaswolf** [comment]
It's been more than two weeks, 9 downloads, and no bug reports. So I'll just assume that no news is good news and promote that release from pre-release to regular release.
