### ISSUE TITLE
Gerrit GitBlit Plugin for Gerrit 2.10.5

### ISSUE THREAD

**Issue by cherylhu** [tomaswolf/gerrit-gitblit-plugin#17]
I want to use the plugin of gitblit. But the version of my gerrit is 2.10.5. I can't find a suitable plugin. Can you send it to me, please? My email address is xiuyun.hu@hisilicon.com.
Thanks very much.

**Comment by tomaswolf** [comment]
I've created a release from the maintenance-2.10 branch for this : [release v2.10.4.162.1](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.10.4.162.1). Should work with all JGit-4-based Gerrit 2.10 versions, i.e., 2.10.4 and higher. Give it a try!

I don't have a Gerrit 2.10 installation anymore, so I can't test myself. Please report back whether it works. It should; basically I only had to cherry-pick a few commits from the master branch; mainly the adaptation to JGit 4, plus some other minor fixes.

**Comment by clouds08** [comment]
Thanks. It can work now. 
I have doubts that how can I configure gitblit and whether gitblit can use caches to make response time shorter. Because I have thousands of projects, so that It costs a very long time when I login to gitblit or click on the button of "Repository".

**Comment by tomaswolf** [comment]
> I have thousands of projects

Whoa! See the README. It says:

* I do _not_ know how well GitBlit scales. It does not seem to be clusterable: according to its author, James Moger,
  "[Gitblit is heavily filesystem based and does not support clustering.](https://groups.google.com/forum/#!topic/gitblit/Puc_3o-zTd0)"
  Additionally, he gives "[Small workgroups that require centralized repositories.](http://gitblit.com/faq.html#H15)" as the target
  audience. I run this plugin for such a group, and it appears to work fine.

I have _no_ idea how, if it's possible at all, Gitblit would need to be configured to perform well with thousands of projects. Maybe ask the author of Gitblit?

**Comment by cherylhu** [comment]
I see it. You are so kind to help me. Thks very much.
