### ISSUE TITLE
Gerrit 2.11.7 Support

### ISSUE THREAD

**Issue by peterpakos** [tomaswolf/gerrit-gitblit-plugin#18]
Is any of your releases fully compatible with Gerrit 2.11.7?

**Comment by tomaswolf** [comment]
I think [release v2.11.3.162.2](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.11.3.162.2) should work; I don't see anything special in the Gerrit release notes of 2.11.6 or 2.11.7 that would indicate otherwise.

**Comment by peterpakos** [comment]
I'll give it a go, thanks.
