### ISSUE TITLE
Clone URLs use sshd.listenAddress instead of sshd.advertisedAddress

### ISSUE THREAD

**Issue by vipuldelwadia** [tomaswolf/gerrit-gitblit-plugin#19]
In my `gerrit.confg`, I have the following:

```
[sshd]
    listenAddress = 10.X.X.X:29418
    advertisedAddress = gerrit.X.com
```

When I view the clone URLs in GitBlit, I see the following:

![gitblit-clone-url](https://cloud.githubusercontent.com/assets/94210/15527164/254f2728-228c-11e6-9fa0-ac1f19bd4b49.png)

i.e. the `ssh://`url is using the `listenAddress` but the `http://`url is using the `advertisedAddress`. The `gerrit.X.com` address is the right one and the ssh clone url is using the wrong one.

Is there a config I can set which fixes this discrepancy?

**Comment by tomaswolf** [comment]
> Is there a config I can set which fixes this discrepancy?

No, there isn't one. I just looked at this code, which was taken over from the "official" plug-in: it's all hard-coded. I'll improve this and provide an updated release.

**Comment by tomaswolf** [comment]
Done in [release 2.12.171.1](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.12.171.1). Please give it a try and report back whether this solves your issue. If so, I'll promote it from "pre-release" to a regular release.

**Comment by vipuldelwadia** [comment]
This works perfectly, thanks for fixing it so quickly!

**Comment by tomaswolf** [comment]
Thanks for reporting back. Release promoted.
