### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by orgads** [tomaswolf/gerrit-gitblit-plugin#20]
Hi,

I have a private project in gerrit, which only a particular group can access.

Still, GitBlit plugin allows even anonymous access to this repository. Is there a way to block it?

**Comment by tomaswolf** [comment]
I have such a project, too, and it is _not_ visible through GitBlit. I suspect a configuration error. Did you set in Gerrit under "Access" for refs/* "Read" permission for both Anonymous Users and Registered Users to DENY?

**Comment by orgads** [comment]
That worked, thanks. I previously set exclusive ALLOW for that group, I guess that's not enough.

**Comment by tomaswolf** [comment]
After having re-read the Gerrit docu, I'm not sure whether ALLOW EXCLUSIVE for one group on refs/* should nullify the inherited (from All-Projects) ALLOW for anons and general registered users. If it should have and didn't, then that's a bug in Gerrit. I've always set these two to DENY when I wanted or needed to restrict access.
