### ISSUE TITLE
support for gerrit 2.14

### ISSUE THREAD

**Issue by stleusc** [tomaswolf/gerrit-gitblit-plugin#29]
Any plan to update the plugin for 2.14?
The official plugin seems to have issues with raw links which always worked on older gerrit with your plugin.

**Comment by tomaswolf** [comment]
I've published [release 2.14.171.0](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.14.171.0). Needed adaptations were really minor; quick tests showed no problems.

Give it a try, and please report back whether it's OK. I'll then promote it from pre-release to regular release.

Note that Gerrit 2.14 requires a Java 8 JRE, and so does this plugin now.

**Comment by stleusc** [comment]
Perfect, quick test here shows that it works nicely!
One thing I noticed is that I can access files via RAW mode even when the user is not logged in.

In other words, a shared/leaked URL to a raw file will return the content, regardless of user authentication.

This is not new and has been like that in all previous version as far as I know.

I actually make use of this 'feature' right now so I'm not even sure I want it fixed ;-).

But then again, access to files in raw mode with mandatory authentication header would be better I guess.

Do you want me to create a separate issue for that? What are your thoughts?

**Comment by tomaswolf** [comment]
Yes, let's deal with that RAW authentication issue separately. But see issue #20 first, and please include the Gerrit config regarding access controls to the project where you experience this if you open an issue for that.
