### ISSUE TITLE
Gerrit breaking change

### ISSUE THREAD

**Issue by gpotzkov** [tomaswolf/gerrit-gitblit-plugin#37]
Hi,

since upgrading to Gerrit 3.1.1 we get the following error when trying to access our repositories with gitblit

`Caused by: java.lang.NoSuchMethodError: com.google.gerrit.server.IdentifiedUser.getAccount()Lcom/google/gerrit/reviewdb/client/Account;`

I think this due to the breaking changes introduced here https://www.gerritcodereview.com/3.1.html#changed-apis-for-id-and-namekey-classes

Please correct me if i'm wrong if not fix it :D

Regards.

**Comment by tomaswolf** [comment]
Try [Release 3.1.171.0](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v3.1.171.0) and please report back whether it works for you.

**Comment by gpotzkov** [comment]
> Try [Release 3.1.171.0](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v3.1.171.0) and please report back whether it works for you.

Thank you for the quick fix. Works like a charm 👍
