### ISSUE TITLE
Release for Gerrit 2.10

### ISSUE THREAD

**Issue by mind-blowing** [tomaswolf/gerrit-gitblit-plugin#4]
Can you please make pre-built release for Gerrit 2.10?

**Comment by tomaswolf** [comment]
Yes, I will. Gerrit 2.10.1, that'll be. Give me a day or two. (Sorry for not responding earlier -- too busy with other stuff.)

However, I have no productive instance of Gerrit 2.10.1. I do have a minimal test setup with Gerrit 2.10.1, but our shop still runs 2.9, so I've got no productive instance to do field testing. That'll be up to you ;-)

**Comment by tomaswolf** [comment]
Pre-built release is [published](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.10.1.162.2). Please test and report back whether or not it works for you.

**Comment by mind-blowing** [comment]
Thanks for the new release, I think we will verify it with Gerrit 2.10.1 in near future.

**Comment by tomaswolf** [comment]
Since the Gerrit API is supposed to remain stable across minor releases, it should also work with a Gerrit 2.10.

**Comment by tomaswolf** [comment]
Closing.

1. This has been tested on my test installation, and I didn't see any problems.
2. No news is good news: since I didn't hear back from you, I presume it also works for you.

If you do encounter problems, feel free to open a new issue.
