### ISSUE TITLE
Gerrit and Gitblit Integration

### ISSUE THREAD

**Issue by santhoshjoy** [tomaswolf/gerrit-gitblit-plugin#6]
I had deployed a gitblit instance and I can able to clone my project and its visible in gitblit UI. Similarly, I have a gerrit UI which currently were not showing any code. Everything is blank. My goal is I have to integrate the gitblit code into gerrit as a code review tool. I tried this http://www.slideshare.net/lucamilanesio/gitblit-plugin-for-gerrit-code-review. I can able to run the maven successfully after clearing so many issues. But in gerrit UI, I can able to see the blank page with gerrit sections. Can you please help what I am doing wrong here.

**Comment by tomaswolf** [comment]
If I understand you right, you have a GitBlit server running, and you have a Gerrit server running. Those two will be completely separate, and that setup has got nothing to do with this plugin.

If you want to build _this_ plugin here, see the "Building" section in the [README.md](https://github.com/tomaswolf/gerrit-gitblit-plugin/blob/master/README.md#building). You'll need Eclipse with maven support and m2e and m2e-apt. Or simply download a [pre-built release](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases).

If you are trying to build the [official plugin](https://gerrit.googlesource.com/plugins/gitblit/), then please see there on how to do it, and if you have problems with that, ask Luca Milanesio in the [repo-discuss forum](https://groups.google.com/forum/?hl=en#!forum/repo-discuss). Or simply download a pre-built jar from https://ci.gerritforge.com/ .
